version: '3.8'

services:
  api:
    image: cotobirthdaybooking.api
    build:
      context: .
      dockerfile: CotoBirthdayBooking.Api/Dockerfile
    ports:
      - "8082:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BirthdayBookingDB;User Id=apiuser;Password=apiuser;
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    depends_on:
      - sqlserver
      - rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Panel de administración web

volumes:
  sqlserverdata:
